<a href="https://colab.research.google.com/github/francescakaganzi/ML/blob/main/01_Python_Introduction_Lab_(Francesca_Kaganzi).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Introduction to Python
#### Date: Sep 06,2023
#### Submission must be made through Github
You are required to complete all tasks correctly (or almost correctly) . You are free to use any material (lecture, Stackoverflow etc.) except full solutions but you should first try to figure them out on your own. We use an nbgrader for partially autograding the assignments. Please DO NOT delete or copy cells. You can add new cells but your solutions should go into the designated cells.

`range()` practice

1 . Print the numbers between 60 and 69 inclusive.

In [ ]:
for i in range(60, 70):
    print(i)

60
61
62
63
64
65
66
67
68
69


2 . Read numbers until 0 and print their mean and standard deviation without using a list.

In [ ]:
import random

count = 0
sum_numbers = 0
sum_squared_numbers = 0

num_values = random.randint(5, 10)
print(f"Generating {num_values} random integers:")

while count < num_values:
    try:
        num = random.randint(1, 100)  # Generate random integers between 1 and 100

        count += 1
        sum_numbers += num
        sum_squared_numbers += num ** 2

        print(num)  # Output the generated integer
    except ValueError:
        print("Invalid input. Please enter a valid integer.")

if count == 0:
    print("No numbers generated.")
else:
    mean = sum_numbers / count
    variance = (sum_squared_numbers / count) - (mean ** 2)
    std_deviation = variance ** 0.5

    print("\nStatistics:")
    print(f"Mean: {mean}")
    print(f"Standard Deviation: {std_deviation}")


3 . Print the odd numbers from this list. `l = [2, 3, -2, -7, 0, 2, 3]`

In [ ]:
l = [2, 3, -2, -7, 0, 2, 3]

for odd in l:
    if odd % 2 != 0:
        print(odd)

odd_number = [odd for odd in l if odd % 2 != 0]
print(*odd_number)

##### Functions
4 . Write a function that takes an integer parameter `(N)` and returns a list of the first `N` prime numbers starting from 2.

In [ ]:
def is_prime(number):
    if number > 1:
        for num in range(2, number // 2 + 1):
            if number % num == 0:
                return False
        return True
    return False


def get_n_primes(N):
    prime_numbers = []
    num = 2
    while len(prime_numbers) < N:
        if is_prime(num):
            prime_numbers.append(num)
        num += 1
    return prime_numbers


# Test
N = 5  # You can change N to any positive integer
primes = get_n_primes(N)
print(primes)

In [ ]:
assert(get_n_primes(3) == [2, 3, 5])
assert(get_n_primes(0) == [])

5. Write a function that takes an integer parameter (N) and returns the Nth Fibonacci number.

 The Fibonacci series is defined as:

$$
F_n = F_{n-1} + F_{n-2} \text{ for } n>1\\
F_0 = 0\\
F_1 = 1
$$

The first few elements of the Fibonacci series are 0, 1, 1, 2, 3, 5, 8, 13 etc.

Raise a `ValueError` if $N<0$.


In [ ]:
def get_nth_fibonacci(n):
    if n < 0:
        raise ValueError('Enter a positive number')
    # First Fibonacci number is 0
    elif n == 0:
        return 0
    # Second Fibonacci number is 1
    elif n == 1:
        return 1
    else:
        return get_nth_fibonacci(n-1)+get_nth_fibonacci(n-2)


# Test
print(get_nth_fibonacci(2))

In [ ]:
assert(get_nth_fibonacci(0) == 0)
assert(get_nth_fibonacci(1) == 1)
assert(get_nth_fibonacci(2) == 1)
assert(get_nth_fibonacci(5) == 5)
assert(get_nth_fibonacci(7) == 13)

try:
    get_nth_fibonacci(-2)
except ValueError:
    pass
else:
    AssertionError("TEST FAILS. Negative index should raise a ValueError.")

6 . Create a function that take a list and a predicate (function with boolean return value) as parameters and returns a new list of those elements which the predicate return True. A predicate is a function that takes one element and return `True` or `False`, for example `is_even`, `is_prime`. If you implemented The following tests should run.


In [ ]:
def filter_with_predicate(input_list, predicate):
    filtered_list = []
    for item in input_list:
        if predicate(item):
            filtered_list.append(item)
    return filtered_list


def is_even(x):
    return x % 2 == 0


def is_odd(x):
    return x % 2 == 1


def is_prime(number):
    if number > 1:
        for num in range(2, number // 2 + 1):
            if number % num == 0:
                return False
        return True
    return False


l1 = [1, 2, 3, 4, 19, 35, 11]
l2 = [1, 4, 9, 16, 25]

# Test 1: Filter l1 odd numbers
filtered_odd = filter_with_predicate(l1, is_odd)
print("l1 Odd numbers:", filtered_odd)

# Test 2: Filter l1 prime numbers
filtered_prime = filter_with_predicate(l1, is_prime)
print("l1 Prime numbers:", filtered_prime)

# Test 3: Filter l2 prime numbers
filtered_prime = filter_with_predicate(l2, is_prime)
print("l2 Prime numbers:", filtered_prime)

In [ ]:
l1 = [1, 2, 3, 4, 19, 35, 11]
l2 = [1, 4, 9, 16, 25]
assert(filter_list(l1, is_odd) == [1, 3, 19, 35, 11])
assert(filter_list(l1, is_prime) == [2, 3, 19, 11])
assert(filter_list(l2, is_prime) == [])

7.  Reduce is a function that applies a two argument function against an accumulator and each element in the sequence (from left to right) to reduce it to a single value. If no initial value is provided, the accumulator is initialized with the return value of the function run on the first two elements of the sequence.

```
reduce([1, 2, 3], product) ---> 6
reduce([1, 2, 3], product, accumulator=10) ---> 60
reduce(["foo", "bar"], string_addition) ---> "foobar"
reduce(["foo", "bar"], string_addition, accumulator="hello") ---> "hellofoobar"
```

In [ ]:
from functools import reduce

l1 = [1, 2, -1, 5]
l2 = ["foo", "bar", "hello"]

def product(x, y):
    return x * y


def string_len_add(x, y):
    return x + len(y)


def reduce(sequence, func, accumulator=None):
    # If no accumulator is provided, initialize it with the first element
    if accumulator is None:
        accumulator = sequence[0]
        start_index = 1
    else:
        start_index = 0

    # Iterate through the sequence and apply the function cumulatively
    for i in range(start_index, len(sequence)):
        accumulator = func(accumulator, sequence[i])

    return accumulator


# Test
#reduce(l1, add) == 7
#reduce(l1, add, 10) == 17
#reduce(l2, string_len_add, 0) == 11

In [ ]:
l1 = [1, 2, -1, 5]
l2 = ["foo", "bar", "hello"]

assert(reduce(l1, add) == 7)
assert(reduce(l1, add, 10) == 17)
assert(reduce(l2, string_len_add, 0) == 11)

8. Use your reduce function for the following operations:

##### a. count the number of odd elements in a list of integers,
##### b. find the maximum of a list of integers,
##### c. find the longest string in list of strings.

``` Test your solutions. ```

In [ ]:
from functools import reduce

l1 = [1, 2, -1, 5]
l2 = ["foo", "bar", "hello"]

# Define a function to count odd numbers
def count_odd(odd, x):
    if x % 2 != 0:
        return odd + 1
    return odd


# Define a function to find the maximum
def find_max(highest, y):
    return max(highest, y)


# Define a function to find the longest string
def find_longest(long, z):
    return long if len(long) >= len(z) else z


# Use reduce to count odd numbers in the list
count = reduce(count_odd, l1, 0)
print(count)

# Use reduce to find the maximum in the list
max_value = reduce(find_max, l1)
print(max_value)

# Use reduce to find the longest string in the list
longest_string = reduce(find_longest, l2)
print(longest_string)

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

9. Create a function that takes a matrix of size NxM and returns the pairwise L2 distance of each row pair.

For input $A^{N \times M}$, the output should be $D^{N \times N}$ where: $D_{i,j} = L_2 (A_i, A_j)$

In [ ]:
import numpy as np

def is_matrix(matrix):
    # Check if the input is a matrix (list of lists) by verifying that all rows have the same length
    return all(len(row) == len(matrix[0]) for row in matrix)

def transpose(matrix):
    # Transpose a matrix (swap rows and columns)
    return [[matrix[j][i] for j in range(len(matrix))] for i in range(len(matrix[0]))]

def pairwise_row_distance(matrix):
    if not is_matrix(matrix):
        raise ValueError("Input is not a valid matrix.")

    # Calculate the pairwise L2 distances using NumPy
    # matrix = np.array(matrix)
    # distances = np.linalg.norm(matrix[:, np.newaxis] - matrix, axis=2)
    # Ensure that the input matrix is a NumPy array for efficient calculations
    matrix = np.array(matrix)


    # Get the number of rows and columns in the matrix
    num_rows, num_cols = matrix.shape

    # Initialize a square matrix to store the pairwise L2 distances
    pairwise_distances = np.zeros((num_rows, num_rows))


    # Calculate the pairwise L2 distances
    for i in range(num_rows):
        for j in range(i, num_rows):
            distance = np.linalg.norm(matrix[i] - matrix[j])
            pairwise_distances[i][j] = distance
            pairwise_distances[j][i] = distance  # The matrix is symmetric

    return pairwise_distances.tolist()

    # return distances.tolist()


D = pairwise_row_distance([[1, 0, 2], [0, 2, 1]])

In [ ]:
D = pairwise_row_distance([[1, 0, 2], [0, 2, 1]])
# should be a matrix
assert is_matrix(D) == True
assert len(D) == 2
assert len(D[0]) == 2
assert D[0][0] == 0
assert abs(D[0][1] - 2.449489742783178) < 1e-3
assert abs(D[1][0] - 2.449489742783178) < 1e-3
assert D[1][1] == 0

# should be symmetric
assert transpose(D) == D

10 . Object Oriented Programming
 Define a class named `A` with a 'constructor' that takes a single parameter and stores it in an attribute named `value`. Add a `print_value` method to the class. Instantiate the class and call the `print_value` method.

In [ ]:
class A:
    def __init__(self, value):
        self.value = value

    def print_value(self):
        print(self.value)


instance = A("abc")
instance.print_value()


In [ ]:
a = A("abc")
a.print_value()

11.  Define a class named `B`, whose `__init__` takes two parameters and stores one in a public attribute and the other in a private attribute named `this_is_public` and `__this_is_private` respectively. Check the class's ``__dict__``  attribute and find out the mangled name of the private attribute.

In [2]:
class B:
    def __init__(self, public_attr, private_attr):
        self.this_is_public = public_attr
        self.__this_is_private = private_attr

# Create an instance of the class B
b = B(1, 2)

# Access the public attribute
print(b.this_is_public)  # Output: public_value

# Accessing the private attribute directly will raise an AttributeError
# print(b.__this_is_private)
try:
    b.__this_is_private
    print("This should not happen.")
except AttributeError:
    print("Failed to access private attribute, this is good :)")


# Check the class's __dict__ attribute to find the mangled name
print(B.__dict__)


1
Failed to access private attribute, this is good :)
{'__module__': '__main__', '__init__': <function B.__init__ at 0x7da3101e5240>, '__dict__': <attribute '__dict__' of 'B' objects>, '__weakref__': <attribute '__weakref__' of 'B' objects>, '__doc__': None}


In [ ]:
b = B(1, 2)
assert b.this_is_public == 1
try:
    b.__this_is_private
    print("This should not happen.")
except AttributeError:
    print("Failed to access private attribute, this is good :)")

13 . Inheritance

###### Guess the output without running the cell.

In [ ]:
class A(object): pass
class B(A): pass
class C(A): pass
class D(B): pass

a = A()
b = B()
c = C()
d = D()

print(isinstance(a, object))
print(isinstance(b, object))
print(isinstance(a, B))
print(isinstance(b, A))
print(isinstance(d, A))

True True False True True

In [ ]:
print(issubclass(C, object))
print(issubclass(D, B))
print(issubclass(B, D))
print(issubclass(B, B))

True True False True

#### Create a Cat, a Dog, a Fish and a Eagle class.

The animals have the following attributes:

1. cats, dogs and eagles can make a sound (this should be a make_sound function that prints the animals sound),
2. all animals have an age and a number_of_legs attribute,
3. cats and dogs have a fur_color attribute. They can be instantiated with a single color or a list or tuple of colors.

Use inheritance and avoid repeating code. Use default values in the constructors.

In [ ]:
class Animal:
    def __init__(self, name, age=0, number_of_legs=0):
        self.name = name
        self.age = age
        self.number_of_legs = number_of_legs

    def make_sound(self):
        pass


class Mammal(Animal):
    def __init__(self, name, age=0, number_of_legs=4, fur_color=None):
        super().__init__(name, age, number_of_legs)
        if fur_color is None:
            fur_color = []
        elif isinstance(fur_color, str):
            fur_color = [fur_color]
        self.fur_color = fur_color


class Cat(Mammal):
    def make_sound(self):
        print(f"{self.name} says 'Meow!'")


class Dog(Mammal):
    def make_sound(self):
        print(f"{self.name} says 'Woof!'")


class Fish(Animal):
    def make_sound(self):
        print(f"{self.name} makes bubbling sounds as it swims.")


class Eagle(Animal):
    def make_sound(self):
        print(f"{self.name} screeches loudly as it soars through the sky.")

# Test
try:
    cat = Cat("Fluffy", age=3, fur_color="white")
    dog = Dog("Cherry", age=1, fur_color=("white", "brown", "black"))
    fish = Fish("King")
    eagle = Eagle("Bruce", age=2)
    animals = [cat, dog, fish, eagle]
except Exception as e:
    print(f'Could not initialize an animal: {e}')

In [ ]:
try:
    cat = Cat("Fluffy", age=3, fur="white")
    dog = Dog("Cherry", age=1, fur=("white", "brown", "black"))
    fish = Fish("King")
    eagle = Eagle("Bruce", age=2)
    animals = [cat, dog, fish, eagle]
except Exception as e:
    print(f'Could not initialize an animal: {e}')

#### Numpy basic exercises

Use vectorization and avoid for loops in all exercises. Implement each exercise as a single function.

##### Implement standardization for 2D arrays.

Standardization is defined as:

\begin{equation*}
X_{std} = \frac{X - \mu}{\sigma},
\end{equation*}

where $\mu$ is the mean of each row and $\rho$ is the standard deviation of each column.

In [6]:
import numpy as np
from mlxtend.preprocessing import standardize

def custom_standardize(X):
    X_std = standardize(X)
    return X_std

X_std = standardize(np.array([[1, 2], [2, 3], [1, 2]]))
X_std

array([[-1.,  1.],
       [-1.,  1.],
       [-1.,  1.]])

#### Implement normalization for 2D arrays.

Normalization is defined as:

\begin{equation*}
X_{norm} = \frac{X - X_{min}}{X_{max} - X_{min}}
\end{equation*}

In [5]:
import numpy as np

def normalize(X):
	# Only this is changed to use 2-norm put 2 instead of 1
	norm = np.linalg.norm(X, 1)
	# normalized matrix
	X = X/norm
	return X

X = np.arange(6).reshape(2, 3)
X[1, 2] = -5
print(X)
normalize(X)

[[ 0  1  2]
 [ 3  4 -5]]


array([[ 0.        ,  0.14285714,  0.28571429],
       [ 0.42857143,  0.57142857, -0.71428571]])

In [ ]:
answer = np.array(
    [[0., 0., 1.],
     [1., 1., 0.]]
)
X_norm = normalize(X)
assert np.allclose(X_norm, answer)